alim/urls.py
from django.urls import path
from .views import *

app_name = 'alim'
urlpatterns = [
    path('',alimIndex,name='index'),
    #path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('create/',alimCreate,name='create'),
    #path('update/<slug:slug>/',alimUpdate,name='update'),
    path('update/<int:id>/',alimUpdate,name='update'),
    #path('delete/<slug:slug>/',alimDelete,name='delete'),
    path('delete/<int:id>/',alimDelete,name='delete'),
]

calisan/urls.py
from django.urls import path
from .views import *

app_name = 'calisan'

urlpatterns = [
    path('',calisanIndex,name='index'),
    path('detail/<slug:slug>/',calisanDetail,name='detail'),
    path('create/',calisanCreate,name='create'),
    path('update/<int:id>/',calisanUpdate,name='update'),
    path('delete/<int:id>/',calisanDelete,name='delete'),
    path('passive/<int:id>/',calisanPassive,name='passive'),
    path('active/<int:id>/',calisanActive,name='active'),
    path('maas/',maasCreate,name='maascreate'),
    path('sgkprim/',sgkprimCreate,name='sgkprimcreate'),
    path('izin/',izinCreate,name='izincreate'),
    path('izin/update/<int:id>/',izinUpdate,name="izinUpdate"),
    path('kart/',kartCreate,name='kartcreate'),
    path('kart/delete/<int:id>/',kartDelete,name='kartDelete'),
]

ekonomiYonetimSistemi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('alim/',include('alim.urls')),
    path('satim/',include('satim.urls')),
    path('calisan/',include('calisan.urls')),
    path('proje/',include('proje.urls')),
    path('urun/',include('urun.urls')),
    path('ciro/',include('ciro.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

calisan/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponseRedirect
from .models import *
from .form import *
from django.contrib import messages
from django.contrib.auth.models import User
from proje.models import *

# Create your views here.

admin_url = "/admin/calisan/calisan"
admin_maas_url = "/admin/calisan/maasodeme"
admin_kart_url = "/admin/calisan/kart"
def calisanIndex(request):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")#25 permission idsi dir.
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    if canView(yetki):
        calisanlar = Calisan.objects.all()
    else:
        calisanlar = Calisan.objects.filter(user = request.user)
    #</Güvenlik>
    yetkiMaas = getAuthorization(request,"maas odeme")
    yetkiSgk = getAuthorization(request,"sgk prim")
    yetkiIzin = getAuthorization(request,"izin")
    yetkiKart = getAuthorization(request,"kart")
    context = {
        'calisanlar':calisanlar,
        'canAdd':canAdd(yetki),
        'canAddMaas':canAdd(yetkiMaas),
        'canAddSgk':canAdd(yetkiSgk),
        'canAddIzin':canAdd(yetkiIzin),
        'canAddKart':canAdd(yetkiKart),
    }
    return render(request,"calisan/index.html",context)
    
def calisanDetail(request,slug):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    if not canView(yetki):
        messages.warning(request,"Çalışan bilgilerine erişim yetkiniz yoktur.")
        return redirect("calisan:index")
        
    #</Güvenlik>
    #yetkiler
    yetkiMaas = getAuthorization(request,"maas odeme")
    yetkiSgk = getAuthorization(request,"sgk prim")
    yetkiIzin = getAuthorization(request,"izin")
    yetkiKart = getAuthorization(request,"kart")
    yetkiEkipUye = getAuthorization(request,"ekip uye")
    yetkiTalep = getAuthorization(request,"talep")

    sgkprimler = False
    maaslar = False
    izinler = False
    kartlar = False
    ekipUyeler = False
    projeTalepler = False
    calisan = get_object_or_404(Calisan,slug = slug)
    if canView(yetkiSgk):
        sgkprimler = SgkPrim.objects.filter(calisan=calisan)
    if canView(yetkiMaas):
        maaslar = MaasOdeme.objects.filter(calisan=calisan)
    if canView(yetkiIzin):
        izinler = Izin.objects.filter(calisan=calisan)
    if canView(yetkiKart):
        kartlar = Kart.objects.filter(calisan=calisan)
    if canView(yetkiEkipUye):
        ekipUyeler = EkipUye.objects.filter(calisan=calisan)
    if canView(yetkiTalep):
        projeTalepler = Talep.objects.filter(calisan=calisan)
    elif calisan.user == request.user:
        projeTalepler = Talep.objects.filter(calisan=calisan)

    
    context = {
        'calisan':calisan,
        'sgkprimler':sgkprimler,
        'maaslar':maaslar,
        'izinler':izinler,
        'kartlar':kartlar,
        'ekipUyeler':ekipUyeler,
        'projeTalepler':projeTalepler,
        #yetkiler
        'canAdd':canAdd(yetki),
        'canChange':canChange(yetki),
        'canAddMaas':canAdd(yetkiMaas),
        'canAddSgk':canAdd(yetkiSgk),
        'canAddIzin':canAdd(yetkiIzin),
        'canChangeIzin':canChange(yetkiIzin),
        'canAddKart':canAdd(yetkiKart),
        'canDeleteKart':canDelete(yetkiKart),
    }
    return render(request,"calisan/calisandetay.html",context)

def calisanCreate(request):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canAdd(yetki):
        messages.warning(request,"Çalışan ekleme yetkiniz yoktur.")
        return redirect("calisan:index")
    #</Güvenlik>
    if request.method == "POST":
        user_form = UserForm(request.POST or None)
        calisan_form = CalisanForm(request.POST or None)
        if user_form.is_valid() and calisan_form.is_valid():
            user = user_form.save(commit = False)
            #user.set_password('cde12345')
            print('girdi1***********************',user_form.cleaned_data['password'])
            if True:#Şifrenin düzgün girildiğinin kontrolü
                print('girdi2***********************')
                #user.set_password(user.password)
                calisan = calisan_form.save(commit = False)
                #user.save()
                user = User.objects.create_user(user_form.cleaned_data['username'],user_form.cleaned_data['email'],user_form.cleaned_data['password'])
                user.is_staff = user_form.cleaned_data['is_staff']
                user.first_name = user_form.cleaned_data['first_name']
                user.last_name = user_form.cleaned_data['last_name']
                user.groups.set(user_form.cleaned_data['groups']) 
                user.user_permissions.set(user_form.cleaned_data['user_permissions'])
                user.save()
                calisan.user = user
                calisan.save()
                messages.success(request,'Çalışan ve user başarılı şekilde oluşturuldu')
            else:
                print('girdi3***********************')
                messages.warning(request,'Şifreyi düzgün girin en az 8 karakter')
        else:
            print('girdi4***********************')
            messages.warning(request,'Lütfen zorunlu alanları dolurunuz.')
    else:
        print('girdi5***********************')
        user_form = UserForm()
        calisan_form = CalisanForm()
    context = {
        'userform':user_form,
        'calisanForm':calisan_form,
        'value':'Ekle',
    }
    return render(request,"calisan/form.html",context)
    #return redirect("{}/add/".format(admin_url))

def calisanUpdate(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canChange(yetki):
        messages.warning(request,"Çalışan güncelleme yetkiniz yoktur.")
        calisan = get_object_or_404(Calisan,id=id)
        return HttpResponseRedirect(calisan.get_absolute_url())
    #</Güvenlik>
    calisan = get_object_or_404(Calisan,id=id)
    calisanForm = CalisanForm(request.POST or None,instance=calisan)
    if request.method == "POST":
        if calisanForm.is_valid():
            calisan = calisanForm.save()
            messages.success(request,'Çalışan başarılı bir şekilde güncellenmiştir.')
            return HttpResponseRedirect(calisan.get_absolute_url())
        else:
            messages.warning(request,'Bir hata oluştu. Lütfen zorunlu alanları doldurunuz.')
    context = {
        'calisanForm':calisanForm,
        'value':'Güncelle',
    }
    return render(request,'calisan/form.html',context)

def calisanDelete(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canDelete(yetki):
        messages.warning(request,"Calışanı silme yetkiniz bulunmamaktadır.")
        return redirect("calisan:index")
    #</Güvenlik>
    return redirect("{}/{}/delete".format(admin_url,id))

def calisanPassive(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canChange(yetki):
        messages.warning(request,"Çalışan güncelleme yetkiniz yoktur.")
        calisan = get_object_or_404(Calisan,id=id)
        return HttpResponseRedirect(calisan.get_absolute_url())
    #</Güvenlik>
    calisan = get_object_or_404(Calisan,id=id)
    user = get_object_or_404(User,id=calisan.user.id)
    user.is_active = False
    user.save()
    messages.success(request,"Kullanıcı engellendi.")
    return HttpResponseRedirect(calisan.get_absolute_url())

def calisanActive(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"calisan")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif canChange:
        messages.warning(request,"Çalışan güncelleme yetkiniz yoktur.")
        calisan = get_object_or_404(Calisan,id=id)
        return HttpResponseRedirect(calisan.get_absolute_url())
    #</Güvenlik>
    calisan = get_object_or_404(Calisan,id=id)
    user = get_object_or_404(User,id=calisan.user.id)
    user.is_active = True
    user.save()
    messages.success(request,"Kullanıcı aktifleştirildi.")
    return HttpResponseRedirect(calisan.get_absolute_url())

def maasCreate(request):
    #<Güvenlik>
    yetki = getAuthorization(request,"maas odeme")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canAdd(yetki):
        messages.warning(request,"Maaş ödeme yetkiniz yoktur.")
        return redirect("calisan:index")
    #</Güvenlik>
    if request.method == "POST":
        
        maasForm = MaasForm(request.POST or None)
        
        if maasForm.is_valid():
            if maasForm.cleaned_data["tumMaas"] == True:
                calisanlar = Calisan.objects.all()
                for i in calisanlar:
                    MaasOdeme.objects.create(calisan=i).save()
                messages.success(request,"Tüm çalışanların maaşları ödendi.")
                return HttpResponseRedirect("/calisan")
            else:
                maasForm.save()
                messages.success(request,"{} ın maaşı ödendi.".format(maasForm.cleaned_data["calisan"]))
                return HttpResponseRedirect(Calisan.objects.get(id = maasForm.cleaned_data["calisan"].id).get_absolute_url())
        else:
            message.warning(request,"Zorunlu alanları doldurun.")
    else:
        maasForm = MaasForm()
    context = {
        'maasForm':maasForm,
        'value':'Maaş Öde',

templates/calisan/calisandetay.html
{% extends "base.html" %}

{% block head %}
    
{% endblock head %}

{% block title %}

{% endblock title %}

{% block body %}

    {%if request.user.is_authenticated %}
        <div class="container">
            <div class="row">
                {% include "calisan/leftnav.html" %}
                <div class="col-sm-10">
                    <div class="row">
                        <div  class="col-sm-9">
                            <div >
                                <a class="thumbnail">
                                <img src="{% if calisan.image %}{{ calisan.image.url }} {% endif %}" alt="Resim Bulunamadı">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <table class="table">
                                    
                                    <tr>
                                        <th>Ad</th> 
                                        <td>{{ calisan.user.get_full_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Tel</th>
                                        <td>{{ calisan.tel }}</td>
                                    </tr>
                                    <tr>
                                        <th>Sgk No</th>
                                        <td>{{ calisan.sgkNo }}</td>
                                    </tr>
                                    <tr>
                                        <th>Maas</th>
                                        <td>{{ calisan.maas }}</td>
                                    </tr>
                                    <tr>
                                        <th>Giriş Yapabilir</th>
                                        <td>{{ calisan.user.is_staff }}</td>
                                    </tr>
                                    <tr>
                                        <th>Aktif</th>
                                        <td>{{ calisan.user.is_active }}</td>
                                    </tr>
                                    {% if canChange %}
                                    <tr>
                                        <td></td>
                                        <td>
                                            <a href="{{ calisan.get_update_url }}" class="btn btn-default" role="button">Düzenle</a>
                                            {% if not calisan.user.is_superuser %}
                                                {% if calisan.user.is_active %}
                                                    <a href="{{ calisan.get_passive_url }}" class="btn btn-danger" role="button">Engelle</a>
                                                {% else %}
                                                    <a href="{{ calisan.get_active_url }}" class="btn btn-danger" role="button">Aktif Yap</a>
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endif %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% if sgkprimler %}
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <div class="panel-heading">Sgk Prim Ödeme Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Ödeme Tarihi</th>
                                    </tr>
                                    {% for sgkprim in sgkprimler %}
                                        <tr>
                                            <td>{{ sgkprim.odemeTarihi }}</td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if maaslar %}
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <div class="panel-heading">Maaş Ödeme Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Ödeme Tarihi</th>
                                    </tr>
                                    {% for maas in maaslar %}
                                        <tr>
                                            <td>{{ maas.tarihi }}</td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if izinler %}
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <div class="panel-heading">Alınan İzin Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Kategori</th>
                                        <th>İzin Tarihi</th>
                                        <th>Gün Sayısı</th>
                                        <th></th>
                                    </tr>
                                    {% for izin in izinler %}
                                        <tr>
                                            <td>{{ izin.kategori }}</td>
                                            <td>{{ izin.izinTarihi }}</td>
                                            <td>{{ izin.gun }}</td>
                                            <td>
                                                {% if canChangeIzin %}
                                                    <a href="{{ izin.get_update_url }}" class="btn btn-default" role="button">Düzenle</a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if kartlar %}
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <div class="panel-heading">Kart Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Kodu</th>
                                        <th></th>
                                    </tr>
                                    {% for kart in kartlar %}
                                        <tr>
                                            <td>{{ kart.kodu }}</td>
                                            <td>
                                                {% if canDeleteKart %}
                                                    <a href="{{ kart.get_delete_url }}" class="btn btn-danger" role="button">Sil</a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if ekipUyeler %}
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <div class="panel-heading">Ekip Proje Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Proje Adı</th>
                                        <th>Ekip Adı</th>
                                        <th>Yetki</th>
                                    </tr>
                                    {% for ekipUye in ekipUyeler %}
                                        <tr>
                                            <td>{{ ekipUye.ekip.proje.adi }}</td>
                                            <td>{{ ekipUye.ekip.adi }}</td>
                                            <td>{{ ekipUye.yetki.adi }}</td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if projeTalepler %}
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="panel panel-default">
                                <div class="panel-heading">Proje Talep Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Proje Adı</th>
                                        <th>Başlık</th>
                                        <th>Talep Tarihi</th>
                                        <th>Kabul Durumu</th>
                                    </tr>
                                    {% for talep in projeTalepler %}
                                        <tr>
                                            <td>{{ talep.proje.adi }}</td>
                                            <td>{{ talep.baslik }}</td>
                                            <td>{{ talep.tarihi }}</td>
                                            <td>{{ talep.kabulDurumu }}</td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {%endif%}
{% endblock body %}

templates/calisan/form.html
{% extends "base.html" %}
{% block head %}

{% load crispy_forms_tags %}
{% endblock head %}
{% block title %}
    Çalışan Ekle
{% endblock title %}
{% block body %}
    
        <div class = "container">
            <div class = "row">
                {% include "calisan/leftnav.html" %}
                <div class = "col-md-8">
                    <form method="POST" enctype = "multipart/form-data">
                        {% csrf_token %}
                        {# {{form.as_p}} #}
                        {{kartForm|crispy}}
                        {{izinForm|crispy}}
                        {{sgkPrimForm|crispy}}
                        {{maasForm|crispy}}
                        {{userform|crispy}}
                        {{userform.media}}
                        {{calisanForm|crispy}}
                        {{calisanForm.media}}{# ckeditor kullanamak için#}
                        <input class = "btn btn-primary" type ="submit" value = "{{value}}" >
                    </form>
                </div>
            </div>
        </div>
    
{% endblock body %}

templates/calisan/index.html
{% extends "base.html" %}

{% block head %}

{% endblock head %}
{% block title %}
    Calışan
{% endblock title %}
{% block body %}
    <div class="container">
        {% include "calisan/leftnav.html" %}
        <div class="col-sm-10">
            {% for calisan in calisanlar %}
                {% if calisan.user.is_active %}
                    <div class="row">
                        
                        <div  class="col-sm-4">
                            <a href="{{ calisan.get_absolute_url }}" class="thumbnail">
                            <img src="{% if calisan.image %}{{ calisan.image.url }} {% endif %}" alt="Resim Bulunamadı">
                            </a>
                        </div>
                        
                        <div class="col-sm-7">
                            <div class="panel panel-default">
                                <table class="table">
                                    
                                    <tr>
                                        <th>Ad</th> 
                                        <td>{{ calisan.user.get_full_name }}</td>
                                    </tr>
                                    <tr>
                                        <th>Tel</th>
                                        <td>{{ calisan.tel }}</td>
                                    </tr>
                                    <tr>
                                        <th>Sgk No</th>
                                        <td>{{ calisan.sgkNo }}</td>
                                    </tr>
                                    <tr>
                                        <th>Maas</th>
                                        <td>{{ calisan.maas }}</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>
                                            <a href="{{ calisan.get_absolute_url }}" class="btn btn-primary" role="button">İncele</a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock body %}

templates/calisan/leftnav.html
<div class="col-sm-2">
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active"><a href="{% url 'calisan:index' %}">Çalışanlar</a></li>
        {% if canAdd %}
            <li role="presentation" class="active"><a href="{% url 'calisan:create' %}">Çalışan Ekle</a></li>
        {% endif %}
        {% if canAddMaas %}
            <li role="presentation" class="active"><a href="{% url 'calisan:maascreate' %}">Maaş Ödeme</a></li>
        {% endif %}
        {% if canAddSgk %}
            <li role="presentation" class="active"><a href="{% url 'calisan:sgkprimcreate' %}">Sgk Prim Ödeme</a></li>
        {% endif %}
        {% if canAddIzin %}
            <li role="presentation" class="active"><a href="{% url 'calisan:izincreate' %}">İzin Ver</a></li>
        {% endif %}
        {% if canAddKart %}
            <li role="presentation" class="active"><a href="{% url 'calisan:kartcreate' %}">Kart Ata</a></li>
        {% endif %}
    </ul>
</div>