alim/urls.py
from django.urls import path
from .views import *

app_name = 'alim'
urlpatterns = [
    path('',alimIndex,name='index'),
    #path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('create/',alimCreate,name='create'),
    #path('update/<slug:slug>/',alimUpdate,name='update'),
    path('update/<int:id>/',alimUpdate,name='update'),
    #path('delete/<slug:slug>/',alimDelete,name='delete'),
    path('delete/<int:id>/',alimDelete,name='delete'),
]

ekonomiYonetimSistemi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('alim/',include('alim.urls')),
    path('satim/',include('satim.urls')),
    path('calisan/',include('calisan.urls')),
    path('proje/',include('proje.urls')),
    path('urun/',include('urun.urls')),
    path('ciro/',include('ciro.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urun/urls.py
from django.urls import path
from .views import *

app_name = 'urun'
urlpatterns = [
    path('',urunIndex,name='index'),
    #path('detail/<slug:slug>/',urunDetail,name='detail'),
    path('create/',urunCreate,name='create'),
    path('update/<slug:slug>/',urunUpdate,name='update'),
    path('delete/<int:id>/',urunDelete,name='delete'),
]

urun/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.

class Urun(models.Model):
    adi = models.CharField(max_length = 120,verbose_name= "Ürün Adı")
    birimFiyati = models.FloatField()
    stokMiktari = models.IntegerField()
    slug = models.SlugField(unique = True,editable = False, max_length= 130)

    def get_update_url(self):
        return reverse("urun:update",kwargs={"slug":self.slug})
    def get_delete_url(self):
        return reverse("urun:delete",kwargs={"id":self.id})
    def get_unique_slug(self):
        slug = slugify(self.adi.replace('ı','i'))
        unique_slug = slug
        counter = 1
        while Urun.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(unique_slug,counter)
            counter += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        super(Urun, self).save(*args, **kwargs)

    def __str__(self):
        return self.adi

urun/views.py
from django.shortcuts import render,HttpResponseRedirect,get_object_or_404,redirect,reverse
from django.contrib import messages
from .models import Urun
from .form import *
from calisan.models import getAuthorization,canAdd,canChange,canDelete,canView
# Create your views here.

admin_url = "/admin/urun/urun"
def urunIndex(request):
    #<Güvenlik>
    yetki = getAuthorization(request,"urun")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    if not canView(yetki):
        messages.warning(request,"Ürünlere erişim yetkiniz yoktur.")
        return redirect("home:index")
        
    #</Güvenlik>
    urunler = Urun.objects.all()
    context = {
        'urunler':urunler,
        'canAdd':canAdd(yetki),
        'canChange':canChange(yetki),
        'canDelete':canDelete(yetki),
    }
    return render(request,'urun/index.html',context)

"""def urunDetail(request,slug):
    urun = get_object_or_404(Urun,slug=slug)
    context = {
        'urun':urun,
    }
    return render(request,"urun/urundetay.html",context)
"""
def urunCreate(request):
    #<Güvenlik>
    yetki = getAuthorization(request,"urun")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canAdd(yetki):
        messages.warning(request,"Ürün ekleme yetkiniz yoktur.")
        return redirect("urun:index")
    #</Güvenlik>
    if request.method == "POST":
        form = UrunYeniForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request,'Ürün başarılı bir şekilde oluşturuldu.')
            return HttpResponseRedirect(reverse("urun:index"))
        else:
            messages.warning(request,'Bir hata oluştu. Lütfen zorunlu alanları doldurunuz.')
    else:
        form = UrunYeniForm()
    context = {
        'form':form,
        'value':'Ürün Oluştur',
    }
    return render(request,"urun/form.html",context)

def urunUpdate(request,slug):
    #<Güvenlik>
    yetki = getAuthorization(request,"urun")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canChange(yetki):
        messages.warning(request,"Ürün güncelleme yetkiniz yoktur.")
        return redirect("urun:index")
    #</Güvenlik>
    if request.method == "POST":
        urun = get_object_or_404(Urun,slug=slug)
        form = UrunForm(request.POST or None,instance = urun)
        if form.is_valid():
            if form.cleaned_data['stok'] > 0:
                urun = form.save(commit=False)
                urun.stokMiktari += form.cleaned_data['stok']
                urun.save()
                messages.success(request,"Stok artırıldı")
                return redirect('urun:index')
            else:
                messages.warning(request,"Lütfen 0 da büyük bir stok miktarı girin")
        else:
            messages.warning(request,"Lütfen zorunlu alanları doldurun")
    else:
        form = UrunForm()
    context = {
        'form':form,
        'value':'Stok Ekle',
    }
    return render(request,"urun/form.html",context)

def urunDelete(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"urun")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canDelete(yetki):
        messages.warning(request,"Ürün silme yetkiniz bulunmamaktadır.")
        return redirect("urun:index")
    #</Güvenlik>
    return redirect("{}/{}/delete".format(admin_url,id))

templates/urun/form.html
{% extends "base.html" %}
{% block head %}

{% load crispy_forms_tags %}
{% endblock head %}
{% block title %}
    Stok Ekle
{% endblock title %}
{% block body %}
    
        <div class = "container">
            <div class = "row">
                {% include "urun/leftnav.html" %}
                <div class = "col-md-8">
                    <form method="POST" enctype = "multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <input class = "btn btn-primary" type ="submit" value = {{value}} >
                    </form>
                </div>
            </div>
        </div>
    
{% endblock body %}

templates/urun/index.html
{% extends "base.html" %}

{% block head %}

{% endblock head %}
{% block title %}
    Alım Liste
{% endblock title %}
{% block body %}
    <div class="container">
        {% include "urun/leftnav.html" %}
        <div class="col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">Alınan Ürün Listesi</div>
                
                <table class="table">
                    <tr>
                        <th>Ürün Adı</th>
                        <th>Birim Fiyatı</th>
                        <th>Stok Miktarı</th>
                        <th></th>
                    </tr>
                    {% for urun in urunler %}
                        <tr>
                            <td>{{ urun.adi }}</td>
                            <td>{{ urun.birimFiyati }}</td>
                            <td>{{ urun.stokMiktari }}</td>
                            <td>
                                {% if canChange %}
                                    <a href="{{ urun.get_update_url }}" class="btn btn-default" role="button">Stok Ekle</a>
                                {% endif %}
                                {% if canDelete %}
                                    <a href="{{ urun.get_delete_url }}" class="btn btn-danger" role="button">Ürünü Sil</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

templates/urun/leftnav.html
<div class="col-sm-2">
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active"><a href="{% url 'urun:index' %}">Ürün</a></li>
        {% if canAdd %}
            <li role="presentation" class="active"><a href="{% url 'urun:create' %}">Ürün Ekle</a></li>
        {% endif %}
    </ul>
</div>