alim/urls.py
from django.urls import path
from .views import *

app_name = 'alim'
urlpatterns = [
    path('',alimIndex,name='index'),
    #path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('create/',alimCreate,name='create'),
    #path('update/<slug:slug>/',alimUpdate,name='update'),
    path('update/<int:id>/',alimUpdate,name='update'),
    #path('delete/<slug:slug>/',alimDelete,name='delete'),
    path('delete/<int:id>/',alimDelete,name='delete'),
]

ekonomiYonetimSistemi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('alim/',include('alim.urls')),
    path('satim/',include('satim.urls')),
    path('calisan/',include('calisan.urls')),
    path('proje/',include('proje.urls')),
    path('urun/',include('urun.urls')),
    path('ciro/',include('ciro.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/urls.py
from django.urls import path
from .views import *

app_name = 'proje'

urlpatterns = [
    path('',projeIndex,name='index'),
    path('detail/<slug:slug>/',projeDetail,name='detail'),
    path('create/',projeCreate,name='create'),
    path('update/<int:id>/',projeUpdate,name='update'),
    path('delete/<int:id>/',projeDelete,name='delete'),
    path('ekip/create/<int:id>/',ekipCreate,name='ekipCreate'),
    path('ekip/update/<int:id>/',ekipUpdate,name='ekipUpdate'),
    path('ekip/delete/<int:id>/',ekipDelete,name='ekipDelete'),
    path('ekipuye/create/<int:id>/',ekipUyeCreate,name='ekipUyeCreate'),
    path('ekipuye/update/<int:id>/',ekipUyeUpdate,name='ekipUyeUpdate'),
    path('ekipuye/delete/<int:id>/',ekipUyeDelete,name='ekipUyeDelete'),
    path('talep/<int:id>/',talepDetail,name='talepDetail'),
    path('talep/create/<slug:slug>/',talepCreate,name='talepCreate'),
]

proje/models.py
from django.db import models
from calisan.models import Calisan, Yetki
from django.utils.text import slugify
from django.urls import reverse
from ciro.models import *

# Create your models here.

class Proje(models.Model):
    adi = models.CharField(max_length=120)
    yoneticiCalisan = models.ForeignKey('calisan.Calisan', related_name='yonetici', on_delete=models.CASCADE,verbose_name="Yönetici")
    slug = models.SlugField(unique = True,editable = False, max_length= 130)

    def get_absolute_url(self):
        return reverse("proje:detail",kwargs={'slug':self.slug})
    def get_create_url(self):
        return reverse("proje:create")
    def get_update_url(self):
        return reverse("proje:update",kwargs={'id':self.id})
    def get_delete_url(self):
        return reverse("proje:delete",kwargs={'id':self.id})

    def get_unique_slug(self):
        slug = slugify(self.adi.replace('ı','i'))
        unique_slug = slug
        counter = 1
        while Proje.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(unique_slug,counter)
            counter += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        super(Proje, self).save(*args, **kwargs)

    def __str__(self):
        return self.adi

class Ekip(models.Model):
    adi = models.CharField(max_length = 50)
    proje = models.ForeignKey('Proje',related_name='EkipProje',on_delete=models.CASCADE,verbose_name="Proje")

    def __str__(self):
        return self.adi

class EkipUye(models.Model):
    ekip = models.ForeignKey('Ekip',related_name='ekip',on_delete=models.CASCADE, verbose_name="Ekip")
    calisan = models.ForeignKey('calisan.Calisan',related_name='EkipUyeCalisan',on_delete=models.CASCADE, verbose_name="Çalışan")
    yetki = models.ForeignKey('calisan.Yetki',related_name='EkipUyeYetki',on_delete=models.CASCADE,verbose_name="Yetki")

    def __str__(self):
        return self.calisan.user.first_name
    
class Talep(models.Model):
    calisan =  models.ForeignKey('calisan.Calisan',related_name='TalepCalisan',on_delete=models.CASCADE, verbose_name="Çalışan")
    baslik = models.CharField(max_length=150,verbose_name="Başlık")
    proje = models.ForeignKey('Proje',related_name='TalepProje',on_delete=models.CASCADE,verbose_name="Proje")
    text = models.TextField(verbose_name="Açıklama")
    tarihi = models.DateTimeField(auto_now_add=True)
    kabulDurumu = models.NullBooleanField(verbose_name="Kabul Durumu")
    maliyet = models.PositiveIntegerField(verbose_name="Maliyet")
    
    def get_absolute_url(self):
        return reverse("proje:talepDetail",kwargs={'id':self.id})

    def save(self, *args, **kwargs):
        ProjeGider.objects.create(talep = self).save()
        super(Talep, self).save(*args, **kwargs)

    def __str__(self):
        return self.baslik

proje/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponseRedirect
from .models import *
from django.contrib import messages
from .form import *
from ciro.models import *
from calisan.models import Calisan,Yetki,getAuthorization,canAdd,canChange,canDelete,canView
admin_url = "/admin/proje/proje"
admin_talep_url = "/admin/proje/talep"
admin_ekip_url = "/admin/proje/ekip"
admin_ekipuye_url = "/admin/proje/ekipuye"
# Create your views here.
def projeIndex(request):
    #<Güvenlik>
    yetki = getAuthorization(request,"proje")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    if canView(yetki):
        projeler = Proje.objects.all()
    else:
        calisan = get_object_or_404(Calisan,user = request.user)
        ekipUyeler = EkipUye.objects.filter(calisan = calisan)
        ekipler = []
        for i in ekipUyeler:
            ekipler.append(Ekip.objects.get(id = i.ekip.id))
        projeler = []
        for i in ekipler:
            projeler.append(Proje.objects.get(id = i.proje.id))
    #</Güvenlik>
    yetkiEkip = getAuthorization(request,"ekip")
    yetkiTalep = getAuthorization(request,"talep")
    context = {
        'projeler':projeler,
        'canAdd':canAdd(yetki),
        'canChange':canChange(yetki),
        'canDelete':canDelete(yetki),
        'canAddEkip':canAdd(yetkiEkip),
        'canAddTalep':canAdd(yetkiTalep),
        
    }
    return render(request,"proje/index.html",context)

def projeDetail(request,slug):
    #<Güvenlik>
    yetki = getAuthorization(request,"proje")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    if not canView(yetki):
        messages.warning(request,"Proje bilgilerine erişim yetkiniz yoktur.")
        return redirect("proje:index")
        
    #</Güvenlik>
    #yetkiler
    yetkiEkip = getAuthorization(request,"ekip")
    yetkiTalep = getAuthorization(request,"talep")
    yetkiEkipUye = getAuthorization(request,"ekip uye")

    proje = get_object_or_404(Proje,slug=slug)
    ekipler = False
    ekipUyeler = False
    projeTalepler = False
    if canView(yetkiEkip):
        ekipler = Ekip.objects.filter(proje = proje)
        if canView(yetkiEkipUye):
            ekipUyeler = list()
            for ekip in ekipler:
                ekipUyeler.append(EkipUye.objects.filter(ekip = ekip))
    if canView(yetkiTalep):
        projeTalepler = Talep.objects.filter(proje = proje)
    
    context = {
        'proje':proje,
        'ekipler':ekipler,
        'ekipUyeler':ekipUyeler,
        'projeTalepler':projeTalepler,
        #yetki
        'canAdd':canAdd(yetki),
        'canChangeEkip':canChange(yetkiEkip),
        'canDeleteEkip':canDelete(yetkiEkip),
        'canAddEkipUye':canAdd(yetkiEkipUye),
        'canChangeEkipUye':canChange(yetkiEkipUye),
        'canDeleteEkipUye':canDelete(yetkiEkipUye),
    }
    return render(request,"proje/projedetay.html",context)

def projeCreate(request): 
    #<Güvenlik>
    yetki = getAuthorization(request,"proje")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canAdd(yetki):
        messages.warning(request,"Proje oluşturma yetkiniz yoktur.")
        return redirect("proje:index")
    #</Güvenlik>
    if request.method == "POST":
        form = ProjeForm(request.POST or None)
        if form.is_valid():
            proje = form.save()
            messages.success(request,'Proje başarılı bir şekilde oluşturuldu.')
            return HttpResponseRedirect(proje.get_absolute_url())
        else:
            messages.warning(request,'Bir hata oluştu. Lütfen zorunlu alanları doldurunuz.')
    else:
        form = ProjeForm()
    context = {
        'form':form,
        'value':'Proje Oluştur',
    }
    return render(request,"proje/form.html",context)

def projeUpdate(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"proje")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canChange(yetki):
        messages.warning(request,"Proje güncelleme yetkiniz yoktur.")
        proje = get_object_or_404(Proje,id=id)
        return HttpResponseRedirect(proje.get_absolute_url())
    #</Güvenlik>
    proje = get_object_or_404(Proje,id=id)
    form = ProjeForm(request.POST or None,instance=proje)
    if request.method == "POST":
        if form.is_valid():
            proje = form.save()
            messages.success(request,'Proje başarılı bir şekilde güncellenmiştir.')
            return HttpResponseRedirect(proje.get_absolute_url())
        else:
            messages.warning(request,'Bir hata oluştu. Lütfen zorunlu alanları doldurunuz.')
    context = {
        'form':form,
        'value':'Güncelle',
    }
    return render(request,'proje/form.html',context)
    return redirect("{}/{}/change".format(admin_url,id))

def projeDelete(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"proje")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canDelete(yetki):
        messages.warning(request,"Proje silme yetkiniz bulunmamaktadır.")
        return redirect("proje:index")
    #</Güvenlik>
    return redirect("{}/{}/delete".format(admin_url,id))

def ekipCreate(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"ekip")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canAdd(yetki):
        messages.warning(request,"Ekip oluşturma yetkiniz yoktur.")
        return redirect("proje:index")
    #</Güvenlik>
    if request.method == "POST":
        form = EkipForm(request.POST or None)
        if form.is_valid():
            ekip = form.save(commit = False)
            ekip.proje = get_object_or_404(Proje,id = id)
            ekip.save()
            messages.success(request,"Ekip başarılı şekilde oluşturuldu")
            yetki = get_object_or_404(Yetki,id = 7)
            for calisan in form.cleaned_data['calisanlar']:
                EkipUye.objects.create(ekip = ekip, calisan = calisan, yetki = yetki).save()
            messages.success(request,"Ekip üyleri eklendi")
            return redirect("proje:index")
        else:
            messages.warning(request,"Zorunlu alanları dolurunuz")
    else:
        form = EkipForm()
    context = {
        'form':form,
        'value':'Ekip Oluştur',
    }
    return render(request,"proje/form.html",context)
def ekipUpdate(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"ekip")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canChange(yetki):
        messages.warning(request,"Ekip güncelleme yetkiniz yoktur.")
        ekip = get_object_or_404(Ekip,id=id)
        return HttpResponseRedirect(ekip.proje.get_absolute_url())
    #</Güvenlik>
    ekip = get_object_or_404(Ekip,id=id)
    form = EkipForm(request.POST or None,instance=ekip)
    if request.method == "POST":
        if form.is_valid():
            ekip = form.save()
            messages.success(request,'Ekip başarılı bir şekilde güncellenmiştir.')
            return HttpResponseRedirect(ekip.proje.get_absolute_url())
        else:
            messages.warning(request,'Bir hata oluştu. Lütfen zorunlu alanları doldurunuz.')
    context = {
        'form':form,
        'value':'Güncelle',
    }
    return render(request,'proje/form.html',context)

def ekipDelete(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"ekip")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canDelete(yetki):
        messages.warning(request,"Ekip silme yetkiniz bulunmamaktadır.")
        return redirect("proje:index")
    #</Güvenlik>
    return redirect("{}/{}/delete".format(admin_ekip_url,id))

def ekipUyeCreate(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"ekip uye")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canAdd(yetki):
        messages.warning(request,"Ekip üyesi ekleme yetkiniz yoktur.")
        return redirect("proje:index")
    #</Güvenlik>
    if request.method == "POST":
        form = EkipUyeForm(request.POST or None)
        if form.is_valid():
            uye = form.save(commit=False)
            ekip = get_object_or_404(Ekip,id = id)
            uye.ekip = ekip
            ekipUyeler = EkipUye.objects.filter(ekip = ekip)
            for i in ekipUyeler:
                print(i,uye, i == uye)
                if i.calisan == uye.calisan:
                    messages.warning(request,"Bu kullanıcı zaten bu ekipte mevcut. Tekrar ekleyemezsiniz.")
                    return HttpResponseRedirect(reverse("proje:ekipUyeCreate",kwargs={'id':id}))
            uye.save()
            messages.success(request,"Ekip üyesi eklendi")
            return HttpResponseRedirect(reverse("proje:detail",kwargs={'slug':uye.ekip.proje.slug}))
        else:
            messages.warning(request,"Zorunlu alanları doldurunuz")
    else:
        form = EkipUyeForm()

    context = {
        'form':form,
        'value':'Üye Ekle'
    }
    return render(request,"proje/form.html",context)

def ekipUyeUpdate(request,id):
    #<Güvenlik>
    yetki = getAuthorization(request,"ekip uye")
    if yetki == -1:
        messages.warning(request,"Erişim için giriş yapınız.")
        return redirect("/admin")
    elif not canChange(yetki):
        messages.warning(request,"Ekip üyelerini güncelleme yetkiniz yoktur.")
        return redirect("proje:index")
    #</Güvenlik>
    ekipUye = get_object_or_404(EkipUye,id=id)
    form = EkipUyeForm(request.POST or None,instance=ekipUye)

templates/proje/form.html
{% extends "base.html" %}
{% block head %}

{% load crispy_forms_tags %}
{% endblock head %}
{% block title %}
    Ekip Ekle
{% endblock title %}
{% block body %}
    
        <div class = "container">
            <div class = "row">
                {% include "proje/leftnav.html" %}
                <div class = "col-md-8">
                    <form method="POST" enctype = "multipart/form-data">
                        {% csrf_token %}
                        {# {{form.as_p}} #}
                        {{form|crispy}}
                        <input class = "btn btn-primary" type ="submit" value = "{{value}}" >
                    </form>
                </div>
            </div>
        </div>
    
{% endblock body %}

templates/proje/index.html
{% extends "base.html" %}

{% block head %}

{% endblock head %}

{% block title %}
    Proje
{% endblock title %}
{% block body %}
    <div class="container">
        {% include "proje/leftnav.html" %}
        <div class="col-sm-10">
            <div class="panel panel-default">
                <div class="panel-heading">Proje Listesi</div>
                
                <table class="table">
                    <tr>
                        <th>Proje Adı</th>
                        <th>Yönetici</th> 
                        <th></th>
                    </tr>
                    {% for proje in projeler %}
                        <tr>
                            <td>{{ proje.adi }}</td>
                            <td>{{ proje.yoneticiCalisan }}</td>
                            <td>
                                <a href="{{ proje.get_absolute_url }}" class="btn btn-primary" role="button">İncele</a>
                                {% if canChange %}
                                    <a href="{{ proje.get_update_url }}" class="btn btn-default" role="button">Düzenle</a>
                                {% endif %}
                                {% if canDelete %}
                                    <a href="{{ proje.get_delete_url }}" class="btn btn-danger" role="button">İptal Et</a>
                                {% endif %}
                                {% if canAddEkip %}
                                    <a href="{% url 'proje:ekipCreate' proje.id %}" class="btn btn-default" role="button">Ekip Ekle</a>
                                {% endif %}
                                {% if canAddTalep %}
                                    <a href="{% url 'proje:talepCreate' proje.slug %}" class="btn btn-primary" role="button">Talep Oluştur</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock body %}

templates/proje/leftnav.html
<div class="col-sm-2">
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active"><a href="{% url 'proje:index' %}">Proje</a></li>
        {% if canAdd %}
            <li role="presentation" class="active"><a href="{% url 'proje:create' %}">Proje Oluştur</a></li>
        {% endif %}
    </ul>
</div>

templates/proje/projedetay.html
{% extends "base.html" %}

{% block head %}
    
{% endblock head %}

{% block title %}

{% endblock title %}

{% block body %}

    {%if request.user.is_authenticated %}
        <div class="container">
            <div class="row">
                {% include "proje/leftnav.html" %}
                
                <div class="col-sm-10">
                {% if ekipler %}
                    {% for ekip in ekipler %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">{{ekip.adi}} Üye Listesi	&nbsp;
                                        {% if canChangeEkip %}
                                            <a href="{% url 'proje:ekipUpdate' ekip.id %}" class="btn btn-default" role="button">Ekibi Düzenle</a>
                                        {% endif %}
                                        {% if canDeleteEkip %}
                                            <a href="{% url 'proje:ekipDelete' ekip.id %}" class="btn btn-danger" role="button">Ekibi Dağıt</a>
                                        {% endif %}
                                        {% if canAddEkipUye %}
                                            <a href="{% url 'proje:ekipUyeCreate' ekip.id %}" class="btn btn-primary" role="button">Üye Ekle</a>
                                        {% endif %}
                                    </div>
                                    {% if ekipUyeler %}
                                    <table class="table">
                                        <tr>
                                            <th>Çalışan Adı</th>
                                            <th>Yetki</th>
                                        </tr>
                                        {% for ekipUye in ekipUyeler %}
                                            {% for i in ekipUye %}
                                                {% if i.ekip == ekip %}
                                                    <tr>
                                                        <td>{{ i.calisan.user.first_name }}</td>
                                                        <td>{{ i.yetki.adi }}</td>
                                                        <td>
                                                            {% if canChangeEkipUye %}
                                                                <a href="{% url 'proje:ekipUyeUpdate' i.id %}" class="btn btn-default" role="button">Düzenle</a>
                                                            {% endif %}
                                                            {% if canDeleteEkipUye %}
                                                                <a href="{% url 'proje:ekipUyeDelete' i.id %}" class="btn btn-danger" role="button">Ekipten Çıkar</a>
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                        {% endfor %}
                                    </table>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% endif %}
                    {% if projeTalepler %}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">Proje Talep Listesi</div>
                                
                                <table class="table">
                                    <tr>
                                        <th>Proje Adı</th>
                                        <th>Başlık</th>
                                        <th>Talep Tarihi</th>
                                        <th>Kabul Durumu</th>
                                        <th></th>
                                    </tr>
                                    {% for talep in projeTalepler %}
                                        <tr>
                                            <td>{{ talep.proje.adi }}</td>
                                            <td>{{ talep.baslik }}</td>
                                            <td>{{ talep.tarihi }}</td>
                                            <td>{{ talep.kabulDurumu }}</td>
                                            <td>
                                                <a href="{{ talep.get_absolute_url }}" class="btn btn-primary" role="button">İncele</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {%endif%}
{% endblock body %}

templates/proje/talepdetay.html
{% extends "base.html" %}

{% block head %}
    
{% endblock head %}

{% block title %}
    Talep Detay
{% endblock title %}

{% block body %}

    {%if request.user.is_authenticated %}
        <div class="container">
            <div class="row">
                {% include "proje/leftnav.html" %}
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <table class="table">
                                    
                                    <tr>
                                        <th>Başlık</th> 
                                        <td>{{ talep.baslik }}</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th>Talep Oluşturan</th>
                                        <td>{{ talep.calisan.user.first_name }}</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th>Tarihi</th>
                                        <td>{{ talep.tarihi }}</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <th>Kabul Durumu</th>
                                        <td>{{ talep.kabulDurumu }}</td>
                                        <td>
                                        {% if talep.kabulDurumu == null %}
                                            <form method = "POST">
                                                {% csrf_token %}
                                                <input type = "submit" name= "kabul" class="btn btn-primary" role="button" value="Kabul Et">
                                                <input type = "submit" name = "red" class="btn btn-danger" role="button" value="Reddet">
                                            </form>
                                        {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Talep İçeriği</th>
                                        <td>{{ talep.text }}</td>
                                        <td></td>
                                    </tr>
                                   
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {%endif%}
{% endblock body %}