alim/urls.py
from django.urls import path
from .views import *

app_name = 'alim'
urlpatterns = [
    path('',alimIndex,name='index'),
    #path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('detail/<slug:slug>/',alimDetail,name='detail'),
    path('create/',alimCreate,name='create'),
    #path('update/<slug:slug>/',alimUpdate,name='update'),
    path('update/<int:id>/',alimUpdate,name='update'),
    #path('delete/<slug:slug>/',alimDelete,name='delete'),
    path('delete/<int:id>/',alimDelete,name='delete'),
]

ciro/urls.py
from django.urls import path
from .views import *

app_name = 'ciro'
urlpatterns = [
    path('',ciroIndex,name='index'),
    #path('detail/<slug:slug>/',ciroDetail,name='detail'),
    #path('create/',ciroCreate,name='create'),
    #path('update/<int:id>/',ciroUpdate,name='update'),
    #path('delete/<int:id>/',ciroDelete,name='delete'),
]

ekonomiYonetimSistemi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('alim/',include('alim.urls')),
    path('satim/',include('satim.urls')),
    path('calisan/',include('calisan.urls')),
    path('proje/',include('proje.urls')),
    path('urun/',include('urun.urls')),
    path('ciro/',include('ciro.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

app_name = 'home'
urlpatterns = [
    path('',homeIndex,name = 'index'),
    path('duyuru/<slug:slug>/',duyuruDetail,name='detail'),
    path('create/',duyuruCreate,name='create'),
    path('update/<slug:slug>/',duyuruUpdate,name='update'),
    path('delete/<slug:slug>/',duyuruDelete,name='delete'),
]

proje/urls.py
from django.urls import path
from .views import *

app_name = 'proje'

urlpatterns = [
    path('',projeIndex,name='index'),
    path('detail/<slug:slug>/',projeDetail,name='detail'),
    path('create/',projeCreate,name='create'),
    path('update/<int:id>/',projeUpdate,name='update'),
    path('delete/<int:id>/',projeDelete,name='delete'),
    path('ekip/create/<int:id>/',ekipCreate,name='ekipCreate'),
    path('ekip/update/<int:id>/',ekipUpdate,name='ekipUpdate'),
    path('ekip/delete/<int:id>/',ekipDelete,name='ekipDelete'),
    path('ekipuye/create/<int:id>/',ekipUyeCreate,name='ekipUyeCreate'),
    path('ekipuye/update/<int:id>/',ekipUyeUpdate,name='ekipUyeUpdate'),
    path('ekipuye/delete/<int:id>/',ekipUyeDelete,name='ekipUyeDelete'),
    path('talep/<int:id>/',talepDetail,name='talepDetail'),
    path('talep/create/<slug:slug>/',talepCreate,name='talepCreate'),
]

urun/urls.py
from django.urls import path
from .views import *

app_name = 'urun'
urlpatterns = [
    path('',urunIndex,name='index'),
    #path('detail/<slug:slug>/',urunDetail,name='detail'),
    path('create/',urunCreate,name='create'),
    path('update/<slug:slug>/',urunUpdate,name='update'),
    path('delete/<int:id>/',urunDelete,name='delete'),
]

templates/base.html
{%load static %}

<html>
    <head>
        
        <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}"/>
        <link rel="stylesheet" href="{% static 'css/style.css'%}"/>
        {% if not request.user.is_authenticated %}
            <meta http-equiv="Refresh" content="0; URL=/admin">
        {% endif %}
            
        {% block head %}
        
        {% endblock head %}

        <title>{% block title %}
        Şirket maliyet yönetim sistemi
        {% endblock title %}</title>
    </head>
    {% if request.user.is_authenticated %}
    <body>
        {% include "header.html" %}
        {% include "message.html" %}
        {% block body %}
        
        {% endblock body %}
        <script type="text/javascript" src = "{%static 'js/jquery.min.js'%}"></scrpit>
        <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></scrpit>
    </body>
    {% endif %}
</html>

templates/header.html
<!-- Navbar Start -->
<head>
        
        
        
</head>
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home:index'%}" class="navbar-brand">Şirket MYS</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <!--
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>
            -->
            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                
                <li><a href="{% url 'home:index'%}">Ana Sayfa</a></li>
                {% if request.session.yetkiAlim == True  %}
                    <li><a href="{% url 'alim:index' %}">Alım</a></li>
                {% endif %}
                {% if request.session.yetkiSatim == True  %}
                    <li><a href="{% url 'satim:index' %}">Satım</a></li>
                {% endif %}
                <li><a href="{% url 'calisan:index' %}">Çalışan</a></li>
                <li><a href="{% url 'proje:index' %}">Proje</a></li>
                {% if request.session.yetkiUrun == True  %}
                    <li><a href="{% url 'urun:index' %}">Ürün</a></li>
                {% endif %}
                {% if request.session.yetkiCiro == True  %}
                    <li><a href="{% url 'ciro:index' %}">Ciro</a></li>
                {% endif %}
                <li><a href="/admin"><b>Admin Paneli ({{ request.user.get_full_name }})</b></a></li>
                
            </ul>

        </nav>

    </div>
</nav>

templates/message.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <div {% if message.tags %}class="alert alert-{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
        {% endfor %}
    </ul>
{% endif %}